package model;
// Generated 24-ene-2019 12:13:45 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private int id;
     private String nombre;
     private float sueldo;
     private char registrado;
     private Date fechaNac;
     private Date horaTutoria;
     private Date fechaRegistro;
     private String observaciones;

    public Alumno() {
    }

    public Alumno(int id, String nombre, float sueldo, char registrado, Date fechaNac, Date horaTutoria, Date fechaRegistro, String observaciones) {
       this.id = id;
       this.nombre = nombre;
       this.sueldo = sueldo;
       this.registrado = registrado;
       this.fechaNac = fechaNac;
       this.horaTutoria = horaTutoria;
       this.fechaRegistro = fechaRegistro;
       this.observaciones = observaciones;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public float getSueldo() {
        return this.sueldo;
    }
    
    public void setSueldo(float sueldo) {
        this.sueldo = sueldo;
    }
    public char getRegistrado() {
        return this.registrado;
    }
    
    public void setRegistrado(char registrado) {
        this.registrado = registrado;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public Date getHoraTutoria() {
        return this.horaTutoria;
    }
    
    public void setHoraTutoria(Date horaTutoria) {
        this.horaTutoria = horaTutoria;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


